using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
// create interface called IExpenseManager in Data Folder. Functions should be AddExpense,UpdateExpense, GetAllExpenses, GetExpensesOnCategory
namespace AssignmentProject.Entities
{
    //properties Id(AutoGenerated),Description, Category,Amount,DateOfExpense 
    // class called expense
    //muse should have a static variable set to a seed no. U should create a constructor and increment this static value and assign to the id property.
    
    public class Expense
    {
        public static int id = 100;
        public int ID { get; private set; } // Id should be auto generated without providing id 
        public string Description { get; set; }
        public string Category { get; set; }

        public double Amount { get; set; }
        public DateTime DateOfExpense { get; set; }
        public Expense()
        {
            ID = ++id;
        }


    }
}
